<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Coe.Ingestion</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Coe.Core\Coe.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
